### ISSUE TITLE
Permalink toolbar doesn't line up with selected line

### ISSUE THREAD

**Issue by fregante** [mattzeunert/OctoTern#12]
> The permalink toolbar doesn't show up on the line you select, but rather about 2 lines above it. 

<img width="250" alt="screen shot 2017-10-31 at 15 31 43" src="https://user-images.githubusercontent.com/1402241/32212143-a52033e0-bde3-11e7-9b32-09b24b8df946.png">

Originally posted in https://github.com/sindresorhus/refined-github/issues/786

**Comment by mattzeunert** [comment]
Hey, thanks for reporting this issue.

Do you have a link to a file where this isn't working? It still looks fine to me.

<img width="289" alt="screen shot 2017-11-07 at 23 47 04" src="https://user-images.githubusercontent.com/1303660/32502557-ab4a74b6-c3a0-11e7-91b2-ec6c66e8ee7d.png">

**Comment by fregante** [comment]
My bad, it's OctoLinker 😅
