### ISSUE TITLE
Scroll to definition

### ISSUE THREAD

**Issue by rreusser** [mattzeunert/OctoTern#3]
This is great! I saw the request for this and hoped someone would make it! A small feature request/suggestion: Is it straightforward/unambiguous to scroll to the definition on click?

![scrolling](https://cloud.githubusercontent.com/assets/572717/15966027/29018450-2eef-11e6-8ed4-d3d043dbb216.gif)

**Comment by rreusser** [comment]
Hmm… looking at the code, it looks like maybe this is implemented and not working for me:

https://github.com/mattzeunert/OctoTern/blob/master/src/process-code-on-page.js#L61-L73

**Comment by mattzeunert** [comment]
It's working fine for me. Can you tell me more about your Chrome version and any extensions that might be interfering?

Best would be if you could have a go at debugging it:

1) In the DevTools sources tab go to "Content Scripts"
2) Open OctoTern/app.js
3) Search for  `$(document.body).animate({` and put a breakpoint in there
4) Does it run? Does it throw an error?

![screen shot 2016-06-10 at 17 29 25](https://cloud.githubusercontent.com/assets/1303660/15971431/ecd43fee-2f30-11e6-9385-1945468a9309.png)

**Comment by rreusser** [comment]
Ah, haven't debugged extensions before. Awesome. Okay. I've disabled all other extensions. Chrome version:

Mac OS X 51.0.2704.84 (Official Build) (64-bit)

Seems legit:

```
> $declarationElements.first().offset().top - heightOfTwoLines
< 483
> $(document.body).animate({scrollTop: 483});
< [<body class=​"logged-in   env-production macintosh vis-public page-blob">​…​</body>​]
```

Just no animation… I usually need `$('html, body')` with scrolling, but the cross-browser thing probably doesn't apply here since chrome only. Nothing immediately jumps out. 😞

**Comment by mattzeunert** [comment]
Any luck with `$("body").scrollTop(465)` or `document.body.scrollTop = 465`?

If those don't work, when you do `$("body").scrollTop()` or `document.body.scrollTop`, is the value updated or still showing the old one?

**Comment by rreusser** [comment]
No luck so far. I think I'll have to get the dev setup running to debug further.

**Comment by mattzeunert** [comment]
That would be awesome!

I've not put much effort into the build instructions. I hope it's fairly straightforward, but if you've got any issues let me know.

**Comment by rreusser** [comment]
`'html,body'` seemed to work. See: #6. Really not sure why it's necessary, but hope it works for everyone! Thanks again! 🎉

**Comment by mattzeunert** [comment]
Interesting! Thanks for looking into it. I'll include the change in the next version.

**Comment by mattzeunert** [comment]
It's in 1.0.4, which should update on the Web Store in a couple of minutes.
