### ISSUE TITLE
Highlight all usages

### ISSUE THREAD

**Issue by jamestalmage** [mattzeunert/OctoTern#4]
Whenever you hover over a variable name (be it in the declaration or a usage), all usages should be highlighted. Currently only the declaration is highlighted.

It would be good if you could also hover over the declaration to see usage as well.

**Comment by mattzeunert** [comment]
Yeah, both things I've been thinking about. Hoping to get this done over the weekend.

**Comment by mattzeunert** [comment]
Ok, I've added this in 1.04.

**Comment by jamestalmage** [comment]
All the recent changes are awesome BTW. I'm really loving this extension.

**Comment by mattzeunert** [comment]
Thanks! Actually, I'm loving it too!
