### ISSUE TITLE
background the tern server?

### ISSUE THREAD

**Issue by jamestalmage** [mattzeunert/OctoTern#7]
It would probably be more efficient to run the tern server in a Chrome [background page](https://developer.chrome.com/extensions/background_pages).

The tern server protocol is [documented here](http://ternjs.net/doc/manual.html#protocol). Rather than communicating over an actual server port, it would probably be best to use extension [messaging](https://developer.chrome.com/extensions/messaging) to communicate between the content script and background page.

Maybe this would improve on the performance issues for large files. (I've not experienced that issue yet, but you mentioned it earlier).

I have pretty limited chrome extension experience, so take this idea with a grain of salt. It's just an idea. Not sure it's a good one.

**Comment by mattzeunert** [comment]
The previous code was resolving all definitions upfront, but I've changed it to only look for definitions when you hover/click. A single Tern request only takes 5ms or so, so it's not noticeable when you hover over things.

Now 90% of the time is spent on DOM manipulations, which I can't move into a separate thread. While there's room for optimization, I don't think it's worth it right now. I've changed it to process files up to 200k characters, which would freeze the page for around 5s on my machine.
