### ISSUE TITLE
Push clicked line to history stack before linking.

### ISSUE THREAD

**Issue by jamestalmage** [mattzeunert/OctoTern#8]
So back button brings you back to the line you clicked.

**Comment by mattzeunert** [comment]
I'm not 100% sure about this. One the one hand I see how it would be useful, on the other hand it could at a lot of items to the history, making it difficult to go to the previous page.

**Comment by jamestalmage** [comment]
I would just as soon have it anyways. If I've been clicking around in the source long enough that I've built up 10+ history items (enough that the back button drop down doesn't show the previous page), then the code is large and confusing enough that the back button has probably already been really helpful to me.

**Comment by mattzeunert** [comment]
I've added this in 1.0.4.

Github normally updates the scroll position when you set the line number in the URL, but I think I've managed to work around that. Let me know if you run into any issues.
