### ISSUE TITLE
Allow private domain?

### ISSUE THREAD

**Issue by oldergod** [mattzeunert/OctoTern#9]
Would you be up to modify the domains the content scripts will run on to - try to - deal with hosted GitHub?

We use `https://github.dev.cybozu.co.jp/` here and I would like to use OctoTern internaly too―without having to fork it, etc.

Not sure though about the right way to go. I don't think a generic `https://*github*/*` is a good solution.
Maybe allow people to add their own repo domain, in my case `https://github.dev.cybozu.co.jp/`.

What do you think? If this does not feel right for you, I'll fork it and customized it for my needs so no pressure.

**Comment by mattzeunert** [comment]
Sorry, I don't think I'll get around to making it work for your scenario. Forking sounds like the best solution.

You have to supply the domains you want to inject your code in in the `manifest.json` file. So it's not possible to add to that later on.

I could ask for permissions to inject code on every page and then check the URL before injecting, but I'd rather avoid asking for excessive permissions.

**Comment by oldergod** [comment]
Okay, no problem. Thank you.
